//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int IdApplication { get; set; }
        public int IdStudent { get; set; }
        public int IdSection { get; set; }
        public System.DateTime ApplicationDate { get; set; }
        public string Status { get; set; }
    
        public virtual Section Section { get; set; }
        public virtual User User { get; set; }
    }
}
