//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KursovayaEntities : DbContext
    {
        public KursovayaEntities()
            : base("name=KursovayaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Application> Application { get; set; }
        public DbSet<Group> Group { get; set; }
        public DbSet<News> News { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<Schedule> Schedule { get; set; }
        public DbSet<Section> Section { get; set; }
        public DbSet<SectionDetail> SectionDetail { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<User> User { get; set; }
    }
}
