//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int IdNews { get; set; }
        public string Title { get; set; }
        public string NewContent { get; set; }
        public System.DateTime Date { get; set; }
        public string Photo { get; set; }
        public Nullable<int> IdAdmin { get; set; }
    
        public virtual User User { get; set; }
    }
}
