//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public Section()
        {
            this.Application = new HashSet<Application>();
            this.Schedule = new HashSet<Schedule>();
        }
    
        public int IdSection { get; set; }
        public string Title { get; set; }
        public string Photo { get; set; }
    
        public virtual ICollection<Application> Application { get; set; }
        public virtual ICollection<Schedule> Schedule { get; set; }
    }
}
