//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Application = new HashSet<Application>();
            this.News = new HashSet<News>();
            this.Schedule = new HashSet<Schedule>();
            this.SectionDetail = new HashSet<SectionDetail>();
        }
    
        public int IdUser { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> IdRole { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
        public Nullable<int> IdGroup { get; set; }
        public Nullable<int> Experience { get; set; }
        public string Photo { get; set; }
    
        public virtual ICollection<Application> Application { get; set; }
        public virtual Group Group { get; set; }
        public virtual ICollection<News> News { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<Schedule> Schedule { get; set; }
        public virtual ICollection<SectionDetail> SectionDetail { get; set; }
    }
}
